sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tharanibabu/LearnDocker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true tharanibabu/LearnDocker-react npm run test -- -- coverage