sudo: required

services:
  - docker

before_install:
  - docker build -t tharanibabu/LearnDocker-react -f Dockerfile.dev .

scripts:
  - docker run tharanibabu/LearnDocker-react npm run test -- -- coverage